# Generated by Django 4.1.2 on 2022-10-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
