# Generated by Django 4.1.2 on 2022-10-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
