# Generated by Django 4.1.2 on 2022-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
